version: "3.9"

services:
  workspaces:
    deploy:
      replicas: 1
    container_name: workspaces
    image: ${WORKSPACES_IMAGE_NAME:-ghcr.io/teradata-tio/workspaces}:${WORKSPACES_IMAGE_TAG:-latest}
    command: serve -v
    restart: unless-stopped
    ports:
      - "443:443/tcp"
      - "3000:3000/tcp"
      - "3282:3282/tcp"
    environment:
      TZ: ${WS_TZ:-UTC}
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
    volumes:
      - ${WORKSPACES_HOME:-./volumes/workspaces}:/etc/td
      - ${WORKSPACES_AWS_CONFIG:-~/.aws}:/root/.aws
  jupyter:
    deploy:
      replicas: 0
    image: ${JUPYTER_IMAGE_NAME:-ghcr.io/teradata-tio/compute-engine-jupyter-kernel}:${JUPYTER_IMAGE_TAG:-latest}
    environment:
      - "accept_license=Y"
    ports:
      - 8888:8888
    volumes:
      - ${JUPYTER_HOME:-./volumes/jupyter}:/home/jovyan/JupyterLabRoot/userdata
