apiVersion: v1
kind: Service
metadata:
  name: regulus-workspaces
  labels:
    app: regulus-workspaces
spec:
  ports:
    - port: 3000
    - port: 3282
  selector:
    app: regulus-workspaces
    tier: workspaces
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: regulus-workspaces-pv-claim
  labels:
    app: regulus-workspaces
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: regulus-workspaces
  labels:
    app: regulus-workspaces
spec:
  selector:
    matchLabels:
      app: regulus-workspaces
      tier: workspaces
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: regulus-workspaces
        tier: workspaces
    spec:
      serviceAccountName: workspaces-service-account
      containers:
      - image: regulus-workspaces:latest
        name: regulus-workspaces
        ports:
        - containerPort: 3000
          name: workspaces-http
        - containerPort: 3282
          name: workspaces-grpc
        volumeMounts:
        - name: regulus-workspaces-persistent-storage
          mountPath: /etc/td
      volumes:
      - name: regulus-workspaces-persistent-storage
        persistentVolumeClaim:
          claimName: regulus-workspaces-pv-claim
